const randomData = [
  {
    vegetarian: true,
    vegan: true,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: true,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 2,
    gaps: "no",
    preparationMinutes: -1,
    cookingMinutes: -1,
    aggregateLikes: 13090,
    healthScore: 12,
    pricePerServing: 18.78,
    extendedIngredients: [
      {
        id: 1002030,
        aisle: "Spices and Seasonings",
        image: "pepper.jpg",
        consistency: "SOLID",
        name: "black pepper",
        nameClean: "black pepper",
        original: "1 tsp black pepper",
        originalName: "black pepper",
        amount: 1.0,
        unit: "tsp",
        meta: ["black"],
        measures: {
          us: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
          metric: { amount: 1.0, unitShort: "tsp", unitLong: "teaspoon" },
        },
      },
      {
        id: 1002014,
        aisle: "Spices and Seasonings",
        image: "ground-cumin.jpg",
        consistency: "SOLID",
        name: "cumin",
        nameClean: "cumin",
        original: "2 tsp cumin",
        originalName: "cumin",
        amount: 2.0,
        unit: "tsp",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "tsps", unitLong: "teaspoons" },
          metric: { amount: 2.0, unitShort: "tsps", unitLong: "teaspoons" },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "SOLID",
        name: "garlic",
        nameClean: "garlic",
        original: "4 Tbsp. jarred minced garlic",
        originalName: "jarred minced garlic",
        amount: 4.0,
        unit: "Tbsp",
        meta: ["jarred", "minced"],
        measures: {
          us: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
          metric: { amount: 4.0, unitShort: "Tbsps", unitLong: "Tbsps" },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "SOLID",
        name: "onion",
        nameClean: "onion",
        original: "1 large onion, chopped",
        originalName: "onion, chopped",
        amount: 1.0,
        unit: "large",
        meta: ["chopped"],
        measures: {
          us: { amount: 1.0, unitShort: "large", unitLong: "large" },
          metric: { amount: 1.0, unitShort: "large", unitLong: "large" },
        },
      },
      {
        id: 16043,
        aisle: "Pasta and Rice;Canned and Jarred",
        image: "pinto-beans.jpg",
        consistency: "SOLID",
        name: "pinto beans",
        nameClean: "pinto beans",
        original: "2 lbs pinto beans",
        originalName: "pinto beans",
        amount: 2.0,
        unit: "lbs",
        meta: [],
        measures: {
          us: { amount: 2.0, unitShort: "lb", unitLong: "pounds" },
          metric: { amount: 907.185, unitShort: "g", unitLong: "grams" },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original:
          "*Up to 2 1/2 Tbsp salt (This is the absolute max if you don't pre-soak your beans.)",
        originalName:
          "Up salt (This is the absolute max if you don't pre-soak your beans.)",
        amount: 1.0,
        unit: "Tbsp",
        meta: ["(This is the absolute max if you don't pre-soak your beans.)"],
        measures: {
          us: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
          metric: { amount: 1.0, unitShort: "Tbsp", unitLong: "Tbsp" },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "10 cups hot water",
        originalName: "hot water",
        amount: 10.0,
        unit: "cups",
        meta: ["hot"],
        measures: {
          us: { amount: 10.0, unitShort: "cups", unitLong: "cups" },
          metric: { amount: 2.366, unitShort: "l", unitLong: "liters" },
        },
      },
    ],
    id: 775585,
    title: 'Crockpot "Refried" Beans',
    readyInMinutes: 45,
    servings: 16,
    sourceUrl:
      "http://penniesandpancakes.blogspot.com/2012/09/crockpot-refried-beans-019-per-cup.html?m=1",
    openLicense: -1,
    image: "https://spoonacular.com/recipeImages/775585-556x370.jpg",
    imageType: "jpg",
    summary:
      'Crockpot "Refried" Beans is a <b>gluten free and vegan</b> hor d\'oeuvre. This recipe makes 16 servings with <b>88 calories</b>, <b>5g of protein</b>, and <b>0g of fat</b> each. For <b>18 cents per serving</b>, this recipe <b>covers 6%</b> of your daily requirements of vitamins and minerals. 13089 people were impressed by this recipe. If you have onion, up salt, garlic, and a few other ingredients on hand, you can make it. From preparation to the plate, this recipe takes roughly <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 84%</b>. This score is amazing. Similar recipes include <a href="https://spoonacular.com/recipes/crockpot-refried-beans-519722">Crockpot Refried Beans</a>, <a href="https://spoonacular.com/recipes/crockpot-refried-beans-640895">Crockpot Refried Beans</a>, and <a href="https://spoonacular.com/recipes/healthy-crockpot-refried-beans-584828">Healthy Crockpot Refried Beans</a>.',
    cuisines: [],
    dishTypes: [
      "antipasti",
      "starter",
      "snack",
      "appetizer",
      "antipasto",
      "hor d'oeuvre",
    ],
    diets: ["gluten free", "dairy free", "lacto ovo vegetarian", "vegan"],
    occasions: [],
    instructions:
      "<p>Rinse the beans in a colander. Pick out any bad beans.</p>Combine all the ingredients in the crockpot. Remove any floating beans. Cover, and cook on HIGH for 4 hours and on LOW for 2 hours.<p><br>Uncover, and remove extra liquid. Leave enough liquid to reach the desired consistency when the beans are mashed. (We like our beans somewhere between the very-liquidy restaurant style beans, and the canned version of refried beans.)</p><p>Mash beans with a potato masher to desired consistency.</p><p>Serve warm. Store in air-tight containers in the refrigerator and use within 2 weeks, or freeze in ziplock bags for later use.</p>",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Rinse the beans in a colander. Pick out any bad beans.",
            ingredients: [
              {
                id: 0,
                name: "beans",
                localizedName: "beans",
                image: "kidney-beans.jpg",
              },
            ],
            equipment: [
              {
                id: 404639,
                name: "colander",
                localizedName: "colander",
                image: "colander.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Combine all the ingredients in the crockpot.",
            ingredients: [],
            equipment: [
              {
                id: 404718,
                name: "slow cooker",
                localizedName: "slow cooker",
                image: "slow-cooker.jpg",
              },
            ],
          },
          {
            number: 3,
            step: "Remove any floating beans. Cover, and cook on HIGH for 4 hours and on LOW for 2 hours.Uncover, and remove extra liquid. Leave enough liquid to reach the desired consistency when the beans are mashed. (We like our beans somewhere between the very-liquidy restaurant style beans, and the canned version of refried beans.)Mash beans with a potato masher to desired consistency.",
            ingredients: [
              {
                id: 16202,
                name: "refried beans",
                localizedName: "refried beans",
                image: "refried-beans.png",
              },
              {
                id: 11352,
                name: "potato",
                localizedName: "potato",
                image: "potatoes-yukon-gold.png",
              },
              {
                id: 0,
                name: "beans",
                localizedName: "beans",
                image: "kidney-beans.jpg",
              },
            ],
            equipment: [
              {
                id: 404763,
                name: "potato masher",
                localizedName: "potato masher",
                image: "potato-masher.jpg",
              },
            ],
            length: { number: 360, unit: "minutes" },
          },
          {
            number: 4,
            step: "Serve warm. Store in air-tight containers in the refrigerator and use within 2 weeks, or freeze in ziplock bags for later use.",
            ingredients: [],
            equipment: [
              {
                id: 221671,
                name: "ziploc bags",
                localizedName: "ziploc bags",
                image: "plastic-bag.jpg",
              },
            ],
          },
        ],
      },
    ],
    sourceName: null,
    creditsText: null,
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/crockpot-refried-beans-775585",
  },
];
